service: VU-Slack-Signup-API
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2
  memorySize: 512
functions:
  submit:
    handler: handler.submitForm
    events:
      - http:
          path: /api/submit
          method: POST
    environment:
      GOOGLE_OAUTH_CLIENT_ID: <ID>
      GOOGLE_OAUTH_CLIENT_SECRET: <SECRET>
      GOOGLE_OAUTH_REFRESH_TOKEN: <TOKEN>