service: VU-Slack-Signup-API
provider:
  name: aws
  runtime: nodejs12.x
  stage: prod
  region: us-east-2
  memorySize: 128
functions:
  test:
    handler: handler.test
    events: 
      - http: 
          path: /api/test
          method: GET
          cors: true
  submit:
    handler: handler.submitForm
    events:
      - http:
          path: /api/submit
          method: POST
          cors: true
    environment:
      GOOGLE_OAUTH_CLIENT_ID: <ID>
      GOOGLE_OAUTH_CLIENT_SECRET: <SECRET>
      GOOGLE_OAUTH_REFRESH_TOKEN: <TOKEN>